# Generated by Django 6.0.7 on 2026-07-12 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(blank=True, help_text='Comma-separated seat numbers', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Base ticket price in INR', max_digits=8),
        ),
        migrations.AddField(
            model_name='theater',
            name='rows',
            field=models.PositiveIntegerField(default=5, help_text='Number of seat rows'),
        ),
        migrations.AddField(
            model_name='theater',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=10, help_text='Seats per row'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube Trailer URL (or embed link)'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='Card', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='movies.booking')),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='movies.showschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('schedule', 'seat_number')},
            },
        ),
    ]
