# Generated by Django 6.0.7 on 2026-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_booking_payment_status_booking_seat_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='screen',
            field=models.CharField(default='Screen 1', help_text='Screen name/number', max_length=50),
        ),
    ]
